import type { Officer, Device, Weather, Zone } from '../types'
import { minutesAgo } from '../utils/format'

export const ZONES: Zone[] = [
  {
    id: 'z1',
    name: 'BRT Tiger Reserve Corridor',
    district: 'Chamrajnagar, Karnataka',
    risk: 'low',
    riskScore: 22,
    lat: 11.9,
    lng: 77.1,
    radius: 0.14,
    officerIds: ['o1', 'o4'],
    elephantCount: 4,
    lastDetection: minutesAgo(46),
    description: 'Forest corridor near BJ College road; historically low cropland incursion.',
  },
  {
    id: 'z2',
    name: 'Muthanga–Wayanad Fringe',
    district: 'Wayanad, Kerala',
    risk: 'high',
    riskScore: 86,
    lat: 11.66,
    lng: 76.22,
    radius: 0.12,
    officerIds: ['o2', 'o3'],
    elephantCount: 9,
    lastDetection: minutesAgo(4),
    description: 'Dense settlement interface with seasonal maize fields; frequent raiding corridor.',
  },
  {
    id: 'z3',
    name: 'Hassan–Sakleshpur Corridor',
    district: 'Hassan, Karnataka',
    risk: 'medium',
    riskScore: 58,
    lat: 12.9,
    lng: 75.79,
    radius: 0.13,
    officerIds: ['o5', 'o1'],
    elephantCount: 6,
    lastDetection: minutesAgo(18),
    description: 'Coffee-estate border section with railway line; movement spikes at dusk.',
  },
  {
    id: 'z4',
    name: 'Valparai–Anamalai Belt',
    district: 'Coimbatore, Tamil Nadu',
    risk: 'low',
    riskScore: 31,
    lat: 10.38,
    lng: 76.95,
    radius: 0.14,
    officerIds: ['o6'],
    elephantCount: 3,
    lastDetection: minutesAgo(120),
    description: 'Tea plantation belt; herd movement mostly contained to shola patches.',
  },
  {
    id: 'z5',
    name: 'Mudumalai Fringe Villages',
    district: 'Nilgiris, Tamil Nadu',
    risk: 'high',
    riskScore: 74,
    lat: 11.58,
    lng: 76.56,
    radius: 0.13,
    officerIds: ['o2', 'o5'],
    elephantCount: 7,
    lastDetection: minutesAgo(9),
    description: 'Village boundary abutting Mudumalai TR; crop raiding reports during harvest.',
  },
]

export const OFFICERS: Officer[] = [
  { id: 'o1', name: 'R. Karthik', role: 'Forest Range Officer', zoneId: 'z1', phone: '+91 94480 22181', status: 'available' },
  { id: 'o2', name: 'S. Meena', role: 'Wildlife Veterinary Surgeon', zoneId: 'z2', phone: '+91 94480 27339', status: 'on-patrol' },
  { id: 'o3', name: 'A. Joseph', role: 'Deputy Range Officer', zoneId: 'z3', phone: '+91 94840 11852', status: 'available' },
  { id: 'o4', name: 'P. Lakshmi', role: 'Field Officer', zoneId: 'z1', phone: '+91 96000 77314', status: 'on-patrol' },
  { id: 'o5', name: 'V. Anand', role: 'Rapid Response Patrol Head', zoneId: 'z5', phone: '+91 90080 44627', status: 'available' },
  { id: 'o6', name: 'K. Divya', role: 'Forest Guard', zoneId: 'z4', phone: '+91 90190 35846', status: 'off-duty' },
]

export const DEVICES: Device[] = [
  { id: 'esp-01', name: 'Edge Node 01 · BRT Gate', zoneId: 'z1', ip: '192.168.1.101', wifiRssi: -52, battery: 92, sensorOk: true, status: 'online', lastComm: minutesAgo(1), firmware: 'gk-v1.4.2', temperature: 34.1, buzzerActive: false },
  { id: 'esp-02', name: 'Edge Node 02 · Muthanga Field', zoneId: 'z2', ip: '192.168.1.102', wifiRssi: -44, battery: 78, sensorOk: true, status: 'online', lastComm: minutesAgo(0), firmware: 'gk-v1.4.2', temperature: 36.8, buzzerActive: false },
  { id: 'esp-03', name: 'Edge Node 03 · Muthanga Maize Belt', zoneId: 'z2', ip: '192.168.1.103', wifiRssi: -67, battery: 64, sensorOk: true, status: 'online', lastComm: minutesAgo(2), firmware: 'gk-v1.4.2', temperature: 37.2, buzzerActive: false },
  { id: 'esp-04', name: 'Edge Node 04 · Sakleshpur Rail Track', zoneId: 'z3', ip: '192.168.1.104', wifiRssi: -84, battery: 41, sensorOk: true, status: 'warning', lastComm: minutesAgo(6), firmware: 'gk-v1.4.0', temperature: 33.5, buzzerActive: false },
  { id: 'esp-05', name: 'Edge Node 05 · Valparai Estate', zoneId: 'z4', ip: '192.168.1.105', wifiRssi: -58, battery: 87, sensorOk: true, status: 'online', lastComm: minutesAgo(3), firmware: 'gk-v1.4.2', temperature: 29.9, buzzerActive: false },
  { id: 'esp-06', name: 'Edge Node 06 · Mudumalai Village 3', zoneId: 'z5', ip: '192.168.1.106', wifiRssi: -49, battery: 71, sensorOk: true, status: 'online', lastComm: minutesAgo(1), firmware: 'gk-v1.4.2', temperature: 30.4, buzzerActive: false },
  { id: 'esp-07', name: 'Edge Node 07 · Mudumalai Village 5', zoneId: 'z5', ip: '192.168.1.107', wifiRssi: -73, battery: 23, sensorOk: false, status: 'offline', lastComm: minutesAgo(96), firmware: 'gk-v1.3.8', temperature: 0, buzzerActive: false },
  { id: 'esp-08', name: 'Edge Node 08 · BRT South Fence', zoneId: 'z1', ip: '192.168.1.108', wifiRssi: -61, battery: 55, sensorOk: true, status: 'online', lastComm: minutesAgo(2), firmware: 'gk-v1.4.2', temperature: 32.2, buzzerActive: false },
  { id: 'esp-09', name: 'Edge Node 09 · Wayanad Approach', zoneId: 'z2', ip: '192.168.1.109', wifiRssi: -55, battery: 66, sensorOk: true, status: 'online', lastComm: minutesAgo(1), firmware: 'gk-v1.4.1', temperature: 35.0, buzzerActive: false },
  { id: 'esp-10', name: 'Edge Node 10 · Hassan Fringe', zoneId: 'z3', ip: '192.168.1.110', wifiRssi: -72, battery: 48, sensorOk: true, status: 'warning', lastComm: minutesAgo(9), firmware: 'gk-v1.4.0', temperature: 34.5, buzzerActive: false },
]

export const WEATHER: Weather = {
  temp: 24,
  humidity: 71,
  windSpeed: 12,
  condition: 'Partly Cloudy',
  rainfall: 'Light in Nilgiris',
  updatedAt: minutesAgo(0),
}

export const MODEL = {
  model: 'YOLOv8n (1280px)',
  accuracy: 94.2,
  mae: 0.31,
  datasetSize: 12840,
  lastTrained: '2025-11-28',
  inferenceMs: 28,
}